spring:
  jpa:
    properties:
      # hibernate custom properties
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl.auto: none
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        show_sql: true
  datasources:
      -
        jdbc-url: jdbc:mysql://localhost:3306/multiple_ds_1?createDatabaseIfNotExist=true
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: P@ssw0rd
        driver-class-name: com.mysql.jdbc.Driver
        validation-query: SELECT * FROM users
        maximum-pool-size: 30
        pool-name: ds1
      -
        jdbc-url: jdbc:mysql://localhost:3306/multiple_ds_2?createDatabaseIfNotExist=true
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: P@ssw0rd
        driver-class-name: com.mysql.jdbc.Driver
        validation-query: SELECT * FROM users
        maximum-pool-size: 30
        pool-name: ds2
flyway:
  enabled: true
  datasources:
    -
      locations: classpath:db/migration/ds1
      schemas: multiple_ds_1
      url: jdbc:mysql://localhost:3306/multiple_ds_1?createDatabaseIfNotExist=true
    -
      locations: classpath:db/migration/ds2
      schemas: multiple_ds_2
      url: jdbc:mysql://localhost:3306/multiple_ds_2?createDatabaseIfNotExist=true