spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    platform: mysql
    url: jdbc:mysql://localhost:3306/springjpa?createDatabaseIfNotExist=true
    initialize: true
    username: root
    password: P@ssw0rd
    driverClassName: com.mysql.jdbc.Driver
    validation-query: SELECT * FROM users
    hikari:
      maximum-pool-size: 30
      connection-timeout: 60000
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl.auto: none
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        show_sql: true